[package]
name = "nldl"
version = "0.1.0"
authors = ["Brandon Cheng <brandon.cheng@protonmail.com>"]
edition = "2021"

[dependencies]
arrayref = "0.3.6"
libc = "0.2.66"
thiserror = "1.0"

[dev-dependencies]
anyhow = "1.0"
