[package]
name = "netlink15_core"
version = "0.1.0"
authors = ["Brandon Cheng <brandon.cheng@protonmail.com>"]
edition = "2018"

[dependencies]
libc = "0.2.66"
thiserror = "1.0"

[dev-dependencies]
anyhow = "1.0"