[package]
publish = false
name = "netlink15_genl"
version = "0.1.0"
authors = ["Brandon Cheng <brandon.cheng@protonmail.com>"]
edition = "2021"

[dependencies]
libc = "0.2.66"
nldl = { path = "../nldl" }
nldl_derive = { path = "../nldl_derive" }
nix = "0.20.2"
thiserror = "1.0"
