[package]
name = "netlink15_genl"
version = "0.1.0"
authors = ["Brandon Cheng <brandon.cheng@protonmail.com>"]
edition = "2021"

[dependencies]
libc = "0.2.66"
nldl = { path = "../nldl" }
netlink15_derive = { path = "../netlink15_derive" }
nix = "0.18.0"
thiserror = "1.0"
